### PR TITLE
Multi Tool

### PR DESCRIPTION
**Pull request by scottf**

### CODE REVIEW

**Comment by ripienaar** [comment]
What’s the purpose of this tool compete to the nats CLI? I am reluctant to inadvertently promote even more tool sprawl by making such a full feature alternative available

**Comment by scottf** [comment]
@ripienaar This is not a tool to compete with the CLI. This is a tool to provide complete exercising and benchmarking of the Java client in regards to JetStream, which cannot be measured with the CLI. Yes, the stream create/delete/info are duplicates of the cli, but that's it. In my documentation (not pushed at the time of your writing) I specifically mention the CLI for these functions
> These functions are provided with our [natscli](https://github.com/nats-io/natscli) command line tool.

**Comment by ColinSullivan1** [comment]
I think it'd be good to add a note like this at the top of the readme.

## About this Tooling

This is a tool to provide complete exercising and benchmarking specific to the NATS Java client with the intent of establishing a baseline for client performance and behavior.

Administration and server related benchmarking of NATS should prefer the [NATS CLI](https://docs.nats.io/nats-tools/natscli) tooling, especially in production environments.

**Comment by scottf** [comment]
I have added the About this Tooling comments to the readme and removed the stream create/delete/info functionality.

**Comment by ripienaar** [comment]
Thank you @scottf

**Review by ColinSullivan1 — APPROVED** [review]
LGTM.

**Pull request merged**
