### PR TITLE
Add quickfix to be able to use auth handler and user info

### PR DESCRIPTION
**Pull request by ryad-eldajani**
When trying to connect to a NATS server with [Auth Callout](https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_callout), the client may be required to use a combination of an auth handler (NKey + Seed) plus user info (username + password). This is working as expected in the go reference implementation.

However, this is not working in the current nats.java implementation, as user info is stripped out when building connection options:

```java
AuthHandler authHandler = Nats.staticCredentials(jwt, nkey);
Options connectOptions = Options.builder()
        .server(config.getUrl())
        .authHandler(authHandler)
        .userInfo(username, password)  
        .build();
```
This PR fixes the behavior in the client options to allow the usage of an auth handler in combination with username and password.

### CODE REVIEW

**Review by scottf — CHANGES_REQUESTED** [review]
I've checked with some other devs. Apparently both should be sent and the server decides
```
if (includeAuth) {
    if (nonce != null && this.getAuthHandler() != null) {
        ...
    }
    // check for user/pass ...
}
```

Also, if possible can you verify your commit? I won't require it for this your first, but for subsequent contributions please verify your commits. [Managing commit signature verification](https://docs.github.com/en/authentication/managing-commit-signature-verification)

**Comment by scottf** [comment]
@ryad-eldajani I messed up your pr, I had made a change to options and it got merged here and overwrote your change and reverted back to before your change. Sorry, can you please update.

**Comment by scottf** [comment]
@ryad-eldajani So my commit contains my original modifying of the includeAuth check, which came before I got the feedback from the developers that it's not one or the other, but you can send both. Please make that change, again sorry for the screwup.

**Comment by ryad-eldajani** [comment]
@scottf Thanks for your valuable feedback. I'll try to redo this change within the next few days, as I'm currently out of office for vacation.

Also, sorry for the missing verification. I have committed this change using my working email address, which is currently not assigned to my personal GPG key. Will keep that in mind on the next PR.

Best regards!

**Comment by ryad-eldajani** [comment]
Hi @scottf thanks for your patience. I have created a new PR based on this discussion. Please see https://github.com/nats-io/nats.java/pull/1138

**Pull request closed without merging**
