### PR TITLE
Switch to Eclipse Temurin and add SDKMan for local dev

### PR DESCRIPTION
**Pull request by artur-ciocanu**
Switch build from AdoptOpenJDK to Eclipse Temurin. Eclipse Temurin is the successor to AdoptOpenJDK and the team behind AdoptOpenJDK recommends switching to Eclipse Temurin. Here are some relevant links: https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/, https://projects.eclipse.org/projects/adoptium.

`.sdkmanrc` - this file is used by SDKMan to switch between different Java versions. This is especially useful when you are working on different repositories and each repository uses a different Java version. SDKMan will use `.sdkmanrc` to switch to the right Java version and set `JAVA_HOME` to the right path. Here is the official SDKMan docs: https://sdkman.io/jdks.

### CODE REVIEW

**Comment by artur-ciocanu** [comment]
Hello @scottf could you please review this tiny PR.

Thank you 🙇‍♀️.

**Comment by scottf** [comment]
@artur-ciocanu Can you please provide some explanation for the reason to make this change.

**Comment by artur-ciocanu** [comment]
> @artur-ciocanu Can you please provide some explanation for the reason to make this change. Please explain why Temurin over Adopt and then why add the ".sdkmanrc" file?

@scottf thanks for your prompt reply. Here are some details:
- Eclipse Temurin - Temurin is the successor to AdoptOpenJDK and the team behind AdoptOpenJDK recommends switching to Eclipse Temurin. Here are some relevant links: https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/, https://projects.eclipse.org/projects/adoptium.
- `.sdkmanrc` - this file is used by SDKMan to switch between different Java versions. This is especially useful when you are working on different repositories and each repository uses a different Java version. SDKMan will use `.sdkmanrc` to switch to the right Java version and set `JAVA_HOME` to the right path. Here is the official SDKMan docs: https://sdkman.io/jdks.

Please let me know if you need additional information. Thank you.

**Review by scottf — APPROVED** [review]
LGTM

**Pull request merged**
